import type { MuseumSite, Ship } from "@/lib/types";

export const sites: MuseumSite[] = [
  {
    id: "site-salem",
    slug: "united-states-naval-shipbuilding-museum",
    name: "United States Naval Shipbuilding Museum",
    city: "Quincy, Massachusetts",
    country: "United States",
    coordinates: [42.2442, -70.9692],
    summary: "A shipbuilding museum centered on the preserved heavy cruiser USS Salem.",
    image: "/placeholder-site.svg",
    shipSlugs: ["uss-salem"],
  },
  {
    id: "site-battleship-cove",
    slug: "battleship-cove",
    name: "Battleship Cove",
    city: "Fall River, Massachusetts",
    country: "United States",
    coordinates: [41.7066, -71.1633],
    summary: "A waterfront museum with a varied fleet spanning battleships, submarines, and destroyers.",
    image: "/placeholder-site.svg",
    shipSlugs: ["uss-massachusetts", "uss-lionfish"],
  },
  {
    id: "site-belfast",
    slug: "hms-belfast-site",
    name: "HMS Belfast",
    city: "London",
    country: "United Kingdom",
    coordinates: [51.5066, -0.0816],
    summary: "The preserved Town-class cruiser moored on the River Thames near Tower Bridge.",
    image: "/placeholder-site.svg",
    shipSlugs: ["hms-belfast"],
  },
  {
    id: "site-victory",
    slug: "portsmouth-historic-dockyard",
    name: "Portsmouth Historic Dockyard",
    city: "Portsmouth",
    country: "United Kingdom",
    coordinates: [50.8019, -1.1094],
    summary: "A major naval heritage destination and home of HMS Victory.",
    image: "/placeholder-site.svg",
    shipSlugs: ["hms-victory"],
  },
  {
    id: "site-mikasa",
    slug: "mikasa-park",
    name: "Mikasa Park",
    city: "Yokosuka",
    country: "Japan",
    coordinates: [35.2851, 139.6744],
    summary: "A waterfront park built around the preserved pre-dreadnought battleship Mikasa.",
    image: "/placeholder-site.svg",
    shipSlugs: ["mikasa"],
  },
  {
    id: "site-aurora",
    slug: "aurora-museum-ship",
    name: "Aurora Museum Ship",
    city: "Saint Petersburg",
    country: "Russia",
    coordinates: [59.9555, 30.3378],
    summary: "The preserved Russian cruiser Aurora on the Petrogradskaya Embankment.",
    image: "/placeholder-site.svg",
    shipSlugs: ["aurora"],
  },
  {
    id: "site-maritiman",
    slug: "maritiman",
    name: "Maritiman",
    city: "Gothenburg",
    country: "Sweden",
    coordinates: [57.7101, 11.9665],
    summary: "A floating maritime museum whose collection includes the destroyer HSwMS Småland.",
    image: "/placeholder-site.svg",
    shipSlugs: ["hswms-smaland"],
  },
];

export const ships: Ship[] = [
  {
    id: "ship-salem",
    slug: "uss-salem",
    name: "USS Salem",
    className: "Des Moines class",
    type: "Heavy cruiser",
    launched: 1947,
    country: "United States",
    siteSlug: "united-states-naval-shipbuilding-museum",
    summary: "The world's only preserved Des Moines-class heavy cruiser and a landmark of Quincy shipbuilding.",
    image: "/placeholder-ship.svg",
  },
  {
    id: "ship-massachusetts",
    slug: "uss-massachusetts",
    name: "USS Massachusetts",
    className: "South Dakota class",
    type: "Battleship",
    launched: 1941,
    country: "United States",
    siteSlug: "battleship-cove",
    summary: "A World War II battleship preserved as the centerpiece of Battleship Cove.",
    image: "/placeholder-ship.svg",
  },
  {
    id: "ship-lionfish",
    slug: "uss-lionfish",
    name: "USS Lionfish",
    className: "Balao class",
    type: "Submarine",
    launched: 1943,
    country: "United States",
    siteSlug: "battleship-cove",
    summary: "A Balao-class fleet submarine open to visitors alongside Battleship Cove's surface ships.",
    image: "/placeholder-ship.svg",
  },
  {
    id: "ship-belfast",
    slug: "hms-belfast",
    name: "HMS Belfast",
    className: "Town class",
    type: "Light cruiser",
    launched: 1938,
    country: "United Kingdom",
    siteSlug: "hms-belfast-site",
    summary: "A Royal Navy cruiser with service from the Arctic convoys to the Korean War.",
    image: "/placeholder-ship.svg",
  },
  {
    id: "ship-victory",
    slug: "hms-victory",
    name: "HMS Victory",
    className: "104-gun first-rate",
    type: "Ship of the line",
    launched: 1765,
    country: "United Kingdom",
    siteSlug: "portsmouth-historic-dockyard",
    summary: "Nelson's flagship at Trafalgar and the oldest commissioned warship in the world.",
    image: "/placeholder-ship.svg",
  },
  {
    id: "ship-mikasa",
    slug: "mikasa",
    name: "Mikasa",
    className: "Mikasa class",
    type: "Pre-dreadnought battleship",
    launched: 1900,
    country: "Japan",
    siteSlug: "mikasa-park",
    summary: "Admiral Togo's flagship at the Battle of Tsushima and a rare surviving pre-dreadnought.",
    image: "/placeholder-ship.svg",
  },
  {
    id: "ship-aurora",
    slug: "aurora",
    name: "Aurora",
    className: "Pallada class",
    type: "Protected cruiser",
    launched: 1900,
    country: "Russia",
    siteSlug: "aurora-museum-ship",
    summary: "A turn-of-the-century cruiser remembered for its association with the October Revolution.",
    image: "/placeholder-ship.svg",
  },
  {
    id: "ship-smaland",
    slug: "hswms-smaland",
    name: "HSwMS Småland",
    className: "Halland class",
    type: "Destroyer",
    launched: 1952,
    country: "Sweden",
    siteSlug: "maritiman",
    summary: "A Cold War Swedish destroyer preserved as part of Gothenburg's floating museum fleet.",
    image: "/placeholder-ship.svg",
  },
];

export const getSite = (slug: string) => sites.find((site) => site.slug === slug);
export const getShip = (slug: string) => ships.find((ship) => ship.slug === slug);
export const getShipsAtSite = (siteSlug: string) => ships.filter((ship) => ship.siteSlug === siteSlug);
